os:
  - windows
  - linux
  - osx

language: c

env:
  - BRANCH=0.20.2
  - BRANCH=1.0.6
  - BRANCH=1.2.4
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"

install:
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble test
